### ISSUE TITLE
Maven Essentials - Can I ask a question here?

### ISSUE THREAD

**Issue by showaid** [prabath/me#1]
Hello,

My name is HyunWoo Jo.
I am currently reading your **Maven Essentials** book.
I learn a lot from the book because It's very concise and practical.
Thank you for your effort.

Anyhow, I am reaching out to you because I have a question regarding to the book.
It's about `mvn dependency:analyze`, but I am not sure here's a good place to ask this type of question.
If you prefer another way of contact, please let me know.

Best regards,
HyunWoo Jo

**Comment by prabath** [comment]
Hi HyunWoo,

Sure.. please send me an email to prabath@apache.org

Thanks & Regards,
-Prabath
